[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = "*"
tokio = { version = "1", features = ["macros"] }
# percy-dom = "0.7.5"
# maud = "*"
stpl = "0.5.0"